excluded:
  - face-mbti/AppDelegate.swift
  - face-mbti/SceneDelegate.swift
  - R.generated.swift
  - Pods

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
