disabled_rules:
  trailing_whitespace

line_length:
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

identifier_name:
  excluded:
    - id
    - URL
    - x
    - y

excluded:
  - Pods
  - R.generated.swift
