# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'face-mbti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for face-mbti
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'

end
